server:
  port: 8443
  servlet:
    session:
      timeout: 1800
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: nicai?
    key-store-type: PKCS12
    key-alias: tomcat
spring:
  thymeleaf:
    cache: false
  datasource:
    primary:
      jdbc-url: jdbc:log4jdbc:mysql://xxx.xxx.xxx.xxx:xxxx/primary_db_name?userUnicode=true&amp;charactorEncoding=UTF-8&amp;autoReconnect=true
      username: root
      password: password
      driver-class-name: net.sf.log4jdbc.DriverSpy
    slave:
      jdbc-url: jdbc:log4jdbc:mysql://xxx.xxx.xxx.xxx:xxxx/slave_db_name?userUnicode=true&amp;charactorEncoding=UTF-8&amp;autoReconnect=true
      username: root
      password: password
      driver-class-name: net.sf.log4jdbc.DriverSpy
  aop:
    auto: true
  messages:
    encoding: UTF-8
    basename: messages/messages